workspace:
  base: /go
  path: src/github.com/josmo/drone-netapp-snapshot
pipeline:
  test:
    image: golang:1.9
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out

  build_linux_amd64:
    image: golang:1.9
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/amd64/drone-netapp-snapshot

  build_linux_arm64:
    image: golang:1.9
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm64
      - CGO_ENABLED=0
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm64/drone-netapp-snapshot

  build_linux_arm:
    image: golang:1.9
    group: build
    environment:
      - GOOS=linux
      - GOARCH=arm
      - CGO_ENABLED=0
      - GOARM=7
    commands:
      - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/linux/arm/drone-netapp-snapshot

  # build_windows_amd64:
  #   image: golang:1.9-nanoserver
  #   group: build
  #   environment:
  #     - GOOS=windows
  #     - GOARCH=amd64
  #     - CGO_ENABLED=0
  #   commands:
  #     - go build -v -ldflags "-X main.build=${DRONE_BUILD_NUMBER}" -a -o release/windows/amd64/drone-webhook

  publish_linux_amd64:
    image: plugins/docker
    username: josmo
    repo: peloton/drone-netapp-snapshot
    auto_tag: true
    secrets: [ docker_password ]
    dockerfile: Dockerfile
    when:
      branch: master
      event: [ push, tag ]

  publish_linux_arm64:
    image: plugins/docker
    username: josmo
    repo: peloton/drone-netapp-snapshot
    auto_tag: true
    auto_tag_prefix: linux-arm64
    secrets: [ docker_password ]
    dockerfile: Dockerfile.arm64
    when:
      branch: master
      event: [ push, tag ]

  publish_linux_arm:
    image: plugins/docker
    username: josmo
    repo: peloton/drone-netapp-snapshot
    auto_tag: true
    auto_tag_prefix: linux-arm
    secrets: [ docker_password ]
    dockerfile: Dockerfile.arm
    when:
      branch: master
      event: [ push, tag ]

  # publish_windows_amd64:
  #   image: plugins/docker
  #   username: josmo
  #   repo: peloton/drone-rancher
  #   tags: [ windows-amd64 ]
  #   secrets: [ docker_password ]
  #   dockerfile: Dockerfile.windows
  #   when:
  #     branch: master
  #     event: push
