FROM microsoft/nanoserver:latest

ENV GODEBUG=netdns=go

LABEL org.label-schema.version=latest
LABEL org.label-schema.vcs-url="https://github.com/josmo/drone-netapp-snapshot.git"
LABEL org.label-schema.name="Drone netapp-snapshot"
LABEL org.label-schema.vendor="Josmo"
LABEL org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-netapp-snapshot /bin/
ENTRYPOINT [ "/bin/drone-netapp-snapshot" ]